"""Unit tests for the sample agents' LLM dispatch paths.

These mock out ``urllib.request.urlopen`` so we never hit the real APIs,
and exercise the order-of-preference logic in ``_call_llm`` plus the
shape of each provider's request and response handling.
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path
from unittest import mock

import pytest

# Make the news agent importable as a module.
_NEWS_AGENT = (
    Path(__file__).resolve().parents[2] / "examples" / "harbin-agent-sample-news" / "agent"
)
if not (_NEWS_AGENT / "run.py").exists():
    pytest.skip("news sample submodule not initialised", allow_module_level=True)


sys.path.insert(0, str(_NEWS_AGENT))
import importlib  # noqa: E402

run = importlib.import_module("run")  # type: ignore[import-not-found]
sys.path.remove(str(_NEWS_AGENT))


class _FakeResponse:
    def __init__(self, payload: dict) -> None:
        self._buf = io.BytesIO(json.dumps(payload).encode("utf-8"))

    def __enter__(self) -> _FakeResponse:
        return self

    def __exit__(self, *a) -> None:
        self._buf.close()

    def read(self) -> bytes:
        return self._buf.read()


def test_offline_brief_is_deterministic() -> None:
    """With no API keys, the synthetic brief still looks like a brief."""
    out = run._build_synthetic_brief()
    assert out.startswith("# News brief · ")
    assert "[source](" in out
    assert "_generated by harbin-agent-sample-news" in out


def test_call_openai_returns_content(monkeypatch) -> None:
    monkeypatch.setenv("OPENAI_API_KEY", "sk-fake")
    captured: dict = {}

    def fake_urlopen(req, timeout=None):
        captured["url"] = req.full_url
        captured["auth"] = req.get_header("Authorization")
        captured["body"] = json.loads(req.data.decode("utf-8"))
        return _FakeResponse({"choices": [{"message": {"content": "FAKE BRIEF"}}]})

    monkeypatch.setattr("urllib.request.urlopen", fake_urlopen)
    out = run._call_openai("hello")
    assert out == "FAKE BRIEF"
    assert captured["url"].endswith("/chat/completions")
    assert captured["auth"] == "Bearer sk-fake"
    assert captured["body"]["messages"][-1]["content"] == "hello"


def test_call_openai_no_key_returns_none(monkeypatch) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    assert run._call_openai("anything") is None


def test_call_anthropic_returns_content(monkeypatch) -> None:
    monkeypatch.setenv("ANTHROPIC_API_KEY", "ant-fake")
    captured: dict = {}

    def fake_urlopen(req, timeout=None):
        captured["url"] = req.full_url
        captured["key"] = req.get_header("X-api-key")
        captured["version"] = req.get_header("Anthropic-version")
        captured["body"] = json.loads(req.data.decode("utf-8"))
        return _FakeResponse(
            {
                "content": [
                    {"type": "text", "text": "FAKE "},
                    {"type": "text", "text": "BRIEF"},
                    # Block of unknown type must be ignored.
                    {"type": "image", "source": {}},
                ]
            }
        )

    monkeypatch.setattr("urllib.request.urlopen", fake_urlopen)
    out = run._call_anthropic("hello")
    assert out == "FAKE BRIEF"
    assert captured["url"].endswith("/v1/messages")
    assert captured["key"] == "ant-fake"
    assert captured["version"] == "2023-06-01"
    assert captured["body"]["messages"][-1]["content"] == "hello"


def test_call_anthropic_no_key_returns_none(monkeypatch) -> None:
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    assert run._call_anthropic("anything") is None


def test_call_anthropic_empty_content_returns_none(monkeypatch) -> None:
    monkeypatch.setenv("ANTHROPIC_API_KEY", "ant-fake")
    monkeypatch.setattr(
        "urllib.request.urlopen",
        lambda req, timeout=None: _FakeResponse({"content": []}),
    )
    assert run._call_anthropic("hi") is None


def test_call_llm_prefers_openai(monkeypatch) -> None:
    """When both keys are set, ``_call_llm`` calls OpenAI first."""
    with mock.patch.object(run, "_call_openai", return_value="OPENAI") as m_open:
        with mock.patch.object(run, "_call_anthropic", return_value="ANT") as m_ant:
            out = run._call_llm("hi")
    assert out == "OPENAI"
    assert m_open.called
    assert not m_ant.called


def test_call_llm_falls_back_to_anthropic(monkeypatch) -> None:
    """If OpenAI returns None, ``_call_llm`` tries Anthropic."""
    with mock.patch.object(run, "_call_openai", return_value=None):
        with mock.patch.object(run, "_call_anthropic", return_value="ANT") as m_ant:
            out = run._call_llm("hi")
    assert out == "ANT"
    assert m_ant.called


def test_call_llm_falls_through_to_none(monkeypatch) -> None:
    """If neither provider returns text, _call_llm returns None."""
    with mock.patch.object(run, "_call_openai", return_value=None):
        with mock.patch.object(run, "_call_anthropic", return_value=None):
            assert run._call_llm("hi") is None
