"""Unit tests for the sample agents' copilot-vs-offline dispatch logic.

These mock ``subprocess.run`` and ``shutil.which`` so the suite never
actually invokes the ``copilot`` binary, and pin the behavior of:

* the ``HARBIN_AGENT_MODE`` env-var override,
* the auto-detect fallback when copilot isn't on PATH,
* the copilot-mode failure → offline-fallback paths for both samples,
* the price-monitor sample's JSON-extraction parser
  (``_parse_copilot_prices``).
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

import pytest

_EX = Path(__file__).resolve().parents[2] / "examples"
_NEWS_AGENT = _EX / "harbin-agent-sample-news" / "agent"
_PM_AGENT = _EX / "harbin-agent-sample-price-monitor" / "agent"

if not (_NEWS_AGENT / "run.py").exists() or not (_PM_AGENT / "run.py").exists():
    pytest.skip("sample submodules not initialised", allow_module_level=True)


def _load(path: Path, name: str):
    sys.path.insert(0, str(path))
    # Make sure we get a fresh module per sample directory.
    sys.modules.pop(name, None)
    mod = importlib.import_module(name)
    sys.path.remove(str(path))
    return mod


news_run = _load(_NEWS_AGENT, "run")
# Re-loading "run" for the price-monitor location requires a clean
# import slate; do it via importlib.util to avoid name collisions.
import importlib.util as _ilu  # noqa: E402

_pm_spec = _ilu.spec_from_file_location("pm_run", _PM_AGENT / "run.py")
assert _pm_spec is not None and _pm_spec.loader is not None
pm_run = _ilu.module_from_spec(_pm_spec)
_pm_spec.loader.exec_module(pm_run)


# ────────────────────────── shared fakes ───────────────────────────


class _FakeProc:
    def __init__(self, *, returncode: int = 0, stdout: str = "", stderr: str = "") -> None:
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


# ────────────────────────── news sample ───────────────────────────


def test_news_offline_brief_is_deterministic() -> None:
    out = news_run._build_synthetic_brief()
    assert out.startswith("# News brief · ")
    assert "[source](" in out
    assert "_generated by harbin-agent-sample-news" in out


def test_news_resolve_mode_explicit_offline(monkeypatch) -> None:
    monkeypatch.setenv("HARBIN_AGENT_MODE", "offline")
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    assert news_run._resolve_mode() == "offline"


def test_news_resolve_mode_explicit_copilot(monkeypatch) -> None:
    monkeypatch.setenv("HARBIN_AGENT_MODE", "copilot")
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: None)
    assert news_run._resolve_mode() == "copilot"


def test_news_resolve_mode_auto_detects_copilot(monkeypatch) -> None:
    monkeypatch.delenv("HARBIN_AGENT_MODE", raising=False)
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    assert news_run._resolve_mode() == "copilot"


def test_news_resolve_mode_auto_falls_back_to_offline(monkeypatch) -> None:
    monkeypatch.delenv("HARBIN_AGENT_MODE", raising=False)
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: None)
    assert news_run._resolve_mode() == "offline"


def test_news_resolve_mode_invalid_value_falls_back(monkeypatch) -> None:
    """Unknown HARBIN_AGENT_MODE values defer to auto-detect (don't crash)."""
    monkeypatch.setenv("HARBIN_AGENT_MODE", "nonsense")
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: None)
    assert news_run._resolve_mode() == "offline"


def test_news_copilot_success(monkeypatch) -> None:
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    captured = {}

    def fake_run(cmd, **kwargs):
        captured["cmd"] = cmd
        captured["input"] = kwargs.get("input")
        return _FakeProc(returncode=0, stdout="  # My brief\n\nbody  ")

    monkeypatch.setattr(news_run.subprocess, "run", fake_run)
    assert news_run._call_copilot("hello") == "# My brief\n\nbody"
    assert captured["cmd"] == [news_run.COPILOT_BIN]
    assert captured["input"] == "hello"


def test_news_copilot_missing_binary_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: None)
    assert news_run._call_copilot("hi") is None


def test_news_copilot_non_zero_exit_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    monkeypatch.setattr(
        news_run.subprocess,
        "run",
        lambda *a, **k: _FakeProc(returncode=42, stderr="boom"),
    )
    assert news_run._call_copilot("hi") is None


def test_news_copilot_empty_stdout_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    monkeypatch.setattr(
        news_run.subprocess,
        "run",
        lambda *a, **k: _FakeProc(returncode=0, stdout="   "),
    )
    assert news_run._call_copilot("hi") is None


def test_news_copilot_timeout_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(news_run.shutil, "which", lambda _name: "/usr/bin/copilot")

    def boom(*a, **k):
        raise news_run.subprocess.TimeoutExpired(cmd="copilot", timeout=1)

    monkeypatch.setattr(news_run.subprocess, "run", boom)
    assert news_run._call_copilot("hi") is None


# ─────────────────────── price-monitor sample ─────────────────────


def test_pm_synthetic_price_is_stable() -> None:
    a = pm_run._synthetic_price("BTC-USD")
    b = pm_run._synthetic_price("BTC-USD")
    assert a == b
    assert pm_run._synthetic_price("BTC-USD") != pm_run._synthetic_price("ETH-USD")


def test_pm_resolve_mode(monkeypatch) -> None:
    monkeypatch.delenv("HARBIN_AGENT_MODE", raising=False)
    monkeypatch.setattr(pm_run.shutil, "which", lambda _name: None)
    assert pm_run._resolve_mode() == "offline"

    monkeypatch.setenv("HARBIN_AGENT_MODE", "copilot")
    assert pm_run._resolve_mode() == "copilot"

    monkeypatch.setenv("HARBIN_AGENT_MODE", "offline")
    monkeypatch.setattr(pm_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    assert pm_run._resolve_mode() == "offline"


def test_pm_parse_copilot_prices_clean_json() -> None:
    out = pm_run._parse_copilot_prices(
        '{"BTC-USD": 75000.5, "ETH-USD": 4200, "GME": null}',
        ["BTC-USD", "ETH-USD", "GME"],
    )
    assert out == {"BTC-USD": 75000.5, "ETH-USD": 4200.0, "GME": None}


def test_pm_parse_copilot_prices_with_fence_and_prose() -> None:
    """Tolerates markdown-fenced JSON with surrounding prose."""
    raw = (
        "Here are the prices you requested:\n\n"
        '```json\n{"BTC-USD": 70000, "ETH-USD": 3500}\n```\n'
        "Hope that helps!"
    )
    out = pm_run._parse_copilot_prices(raw, ["BTC-USD", "ETH-USD"])
    assert out == {"BTC-USD": 70000.0, "ETH-USD": 3500.0}


def test_pm_parse_copilot_prices_unknown_id_becomes_none() -> None:
    """If copilot omits an id, it surfaces as None (not missing)."""
    out = pm_run._parse_copilot_prices('{"BTC-USD": 100}', ["BTC-USD", "ETH-USD"])
    assert out == {"BTC-USD": 100.0, "ETH-USD": None}


def test_pm_parse_copilot_prices_garbage_returns_none() -> None:
    assert pm_run._parse_copilot_prices("absolutely not json", ["X"]) is None


def test_pm_parse_copilot_prices_empty_string_returns_none() -> None:
    assert pm_run._parse_copilot_prices("", ["X"]) is None


def test_pm_call_copilot_success(monkeypatch) -> None:
    monkeypatch.setattr(pm_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    monkeypatch.setattr(
        pm_run.subprocess,
        "run",
        lambda *a, **k: _FakeProc(returncode=0, stdout='{"BTC-USD": 12345}'),
    )
    out = pm_run._call_copilot([{"id": "BTC-USD", "label": "Bitcoin"}], "")
    assert out == {"BTC-USD": 12345.0}


def test_pm_call_copilot_missing_binary_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(pm_run.shutil, "which", lambda _name: None)
    assert pm_run._call_copilot([{"id": "X"}], "") is None


def test_pm_call_copilot_unparseable_returns_none(monkeypatch) -> None:
    monkeypatch.setattr(pm_run.shutil, "which", lambda _name: "/usr/bin/copilot")
    monkeypatch.setattr(
        pm_run.subprocess,
        "run",
        lambda *a, **k: _FakeProc(returncode=0, stdout="nope"),
    )
    assert pm_run._call_copilot([{"id": "X"}], "") is None
